FROM php:8.2.4-apache

RUN apt-get update && apt-get install -y libonig-dev && \

docker-php-ext-install pdo_mysql mysqli mbstring 

ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions pdo_pgsql